### ISSUE TITLE
Rename repo to transportation.austintexas.io

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/transportation.austintexas.io#256]
To make things simpler for onboarding, what if we renamed this repo to the name of its url? transportation.austintexas.io

The `transportation-`naming convention is nice, but is it necessary?

**Comment by johnclary** [comment]
i like that transportation.austintexas.io is more explicit. i'm for it.

related, as i've been working with zenhub i've noticed that having long repo names prefixed with `transportation-` is annoying because on the kanban cards the names get truncated to something like `transportation-d..`

not a fan of using our acronym but it **would** make the repo names nice and short. e.g., `atd-data-publishing` , etc. cc @amenity

**Comment by amenity** [comment]
Definitely support `atd-` in this case.  🚌

**Comment by johnclary** [comment]
solved: let's just prefix with `🚌`. e.g, `🚌-data-publishing`.

**Comment by mateoclarke** [comment]
That would be cool, but you can't name repos with emoji characters. think its gonna be `atd-`

**Comment by johnclary** [comment]
cool. let's do it. would you take care of renaming everything @mateoclarke?

**Comment by mateoclarke** [comment]
This repo has now been renamed to `transportation.austintexas.io`
